# General info
[package]
name = "whitebeam-installer"
version = "0.2.6"
authors = ["WhiteBeam Security, Inc."]
edition = "2018"

# Build targets
[[bin]]
name = "whitebeam-installer"
path = "main.rs"

# Cross-platform dependencies
[dependencies]
libc = { version = "0.2" }
