# General info
[package]
name = "libwhitebeam"
version = "0.2.6"
authors = ["WhiteBeam Security, Inc."]
edition = "2018"

# Build targets
[lib]
name = "whitebeam"
path = "lib.rs"
crate-type = ["cdylib"]

# Cross-platform dependencies
[dependencies]
libc = { version = "^0.2.98" }
rusqlite = { version = "0.26", features = ["bundled"] }
linkme = { version = "0.2" }
automod = { version = "1.0" }
glob = { version = "0.3" }
syslog = { version = "5.0" }
# Cryptographic dependencies
sha3 = { version = "0.9" }
blake3 = { version = "1.0" }
argon2 = { version = "0.3" }

[features]
whitelist_test = []
